name: Upload Artifact

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Yuan-Public-Workspace-main.zip . -x .github/* .git/*

      - run: |
          mkdir -p dist
          mv Yuan-Public-Workspace-main.zip dist/Yuan-Public-Workspace-main.zip

      - name: Deploy Workbench on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
